# Generated by Django 6.0.6 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_bill_grand_total_bill_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_no',
            field=models.CharField(default='INV001', max_length=20),
        ),
    ]
