# Generated by Django 6.0.6 on 2026-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('low_stock_limit', models.IntegerField(default=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logo/')),
            ],
        ),
    ]
