# Generated by Django 6.0.6 on 2026-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_settings_storeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
